// simsports-chrono-dunk/src/layout/index.tsx
// <!-- layout -->
import React from "react";

import { Outlet } from "react-router-dom";

import HeaderView from "./header-view";
import FooterView from "./footer-view";

const View: React.FC = () => {
	return (
		<>
			<main className="relative z-50 max-w-[100vw] w-full overflow-x-hidden">
				<HeaderView />
				<main className="relative w-full min-h-[calc(100vh-var(--sm-layout-height))]">
					<Outlet />
				</main>
				<FooterView />
			</main>
		</>
	);
};

export default View;

// simsports-2.0-pc/src/view/Layout/index.vue
<!-- 导航栏 -->
<template>
	<HeaderView></HeaderView>
	<div class="main_box"><router-view></router-view></div>
	<FooterView></FooterView>
</template>

<script setup lang="ts">
// import { ref, reactive } from "vue";
import HeaderView from "./HeaderTab/index.vue";
import FooterView from "./FooterTab/index.vue";
</script>

<style lang="less" scoped>
.main_box {
	min-height: calc(100vh - 0.86rem);
}
</style>
