// simsports-5.0-moblie/src/views/simdunk/simdunk-palyer-menu/index.tsx
// simdunk-game
import React, { useState, useEffect } from "react";

import GamePalyerMenu from "./game-palyer-menu/index";
import GamePalyer from "./game-palyer/index";

import { urPlayerDate, ssrPlayerDate, srPlayerDate, rPlayerDate, nPlayerDate } from "./simdunkpalyer"; //simdunkpalyer数据
const View: React.FC = () => {
	const [loading, setLoading] = useState<boolean>(true); //等待数据加载完毕
	const [display, setDisplay] = useState<boolean>(true); //定义显示组件
	const [palyerType, setPalyerType] = useState<string>(""); //定义palyer类型
	const [palyerData, setPalyerData] = useState({}); //定义palyer数据
	// 修改Palyer数据
	const changPalyer = () => {
		setLoading(true);
		if (palyerType === "UR") {
			setPalyerData(urPlayerDate);
			setLoading(false);
		} else if (palyerType === "SSR") {
			setPalyerData(ssrPlayerDate);
			setLoading(false);
		} else if (palyerType === "SR") {
			setPalyerData(srPlayerDate);
			setLoading(false);
		} else if (palyerType === "R") {
			setPalyerData(rPlayerDate);
			setLoading(false);
		} else if (palyerType === "N") {
			setPalyerData(nPlayerDate);
			setLoading(false);
		}
	};
	// 修改PalyerType数据
	const handlePalyerChange = (display: boolean, palyerType: string) => {
		setDisplay(display);
		setPalyerType(palyerType);
	};
	// 监听PalyerType的变换
	useEffect(() => {
		changPalyer();
	}, [palyerType]);
	return (
		<>
			<div className="simdunk-game">
				{display ? (
					<GamePalyerMenu display={display} onHandlePalyerChange={handlePalyerChange} />
				) : (
					<>
						{loading ? <></> : <GamePalyer display={display} onHandlePalyerChange={handlePalyerChange} palyerData={palyerData} />}
					</>
				)}
			</div>
		</>
	);
};

export default View;

// simsports-5.0-pc/src/views/simdunk/simdunk-palyer-menu/index.vue
<!-- simdunk-game -->
<template>
	<GamePalyerMenu v-if="exhibitData.display" :exhibit-data="exhibitData"></GamePalyerMenu>
	<GamePalyer v-else :exhibit-data="exhibitData" :palyer-data="palyerData.obj"></GamePalyer>
</template>

<script setup lang="ts">
import { reactive, watch } from "vue";
import GamePalyerMenu from "./game-palyer-menu/index.vue";
import GamePalyer from "./game-palyer/index.vue";

import { urPlayerDate, ssrPlayerDate, srPlayerDate, rPlayerDate, nPlayerDate } from "./simdunkpalyer"; //simdunkpalyer数据
// 展示数据
const exhibitData = reactive({
	display: true, //显示数据
	playerType: "", //player类型
});
// palyer数据
const palyerData = reactive({
	obj: {},
});
// 修改palyer数据
const changPalyerData = () => {
	if (exhibitData.playerType === "UR") {
		palyerData.obj = urPlayerDate;
	} else if (exhibitData.playerType === "SSR") {
		palyerData.obj = ssrPlayerDate;
	} else if (exhibitData.playerType === "SR") {
		palyerData.obj = srPlayerDate;
	} else if (exhibitData.playerType === "R") {
		palyerData.obj = rPlayerDate;
	} else if (exhibitData.playerType === "N") {
		palyerData.obj = nPlayerDate;
	}
};
watch([() => exhibitData.playerType], async () => {
	await changPalyerData();
});
</script>

<style lang="less" scoped></style>
