// simsports-5.0-moblie/src/views/simdunk/index.tsx
// simdunk
import React from "react";
import SimdunkCarousel from "./simdunk-carousel/index";
import SimdunkIntroduce from "./simdunk-introduce/index";
// import SimdunkPalyer from "./simdunk-palyer/index";
import SimdunkPalyerMenu from "./simdunk-palyer-menu/index";
import SimdunkEarn from "./simdunk-earn/index";

const View: React.FC = () => {
	return (
		<>
			<SimdunkCarousel />
			<SimdunkIntroduce />
			{/* <SimdunkPalyer /> */}
			<SimdunkPalyerMenu />
			<SimdunkEarn />
		</>
	);
};

export default View;

// simsports-5.0-pc/src/views/simdunk/index.vue
<!-- game-simdunk -->
<template>
	<SimdunkCarousel />
	<SimdunkIntroduce />
	<!-- <SimdunkPalyer /> -->
	<SimdunkPalyerMenu />
	<SimdunkEarn />
</template>

<script setup lang="ts">
// import { ref, reactive } from "vue";
import SimdunkCarousel from "./simdunk-carousel/index.vue";
import SimdunkIntroduce from "./simdunk-introduce/index.vue";
// import SimdunkPalyer from "./simdunk-palyer/index.vue";
import SimdunkPalyerMenu from "./simdunk-palyer-menu/index.vue";
import SimdunkEarn from "./simdunk-earn/index.vue";
</script>

<style lang="less" scoped></style>
