// simsports-5.0-moblie/src/views/information/privacy-policy/index.tsx
// privacy-policy
import React from "react";
import "../index.less";

const View: React.FC = () => {
	return (
		<div className="main">
			<div className="information-box">
				<p className="information-time">Last updated: December 11, 2023</p>
				<h1>Privacy Policy</h1>
				<h2>1.Introduce</h2>
				<p>
					1.1 METAPROPHET PTE. LTD. ("MP") recognizes that people who use our products pay great attention to their privacy. This
					privacy policy provides detailed information on the website (https://simsports.io) which collect, use, and disclose
					important user information on the MP website ("Website") and the game named SimDunk ("Game"). MP provides this privacy
					policy to help you understand how we use your personal information and how we choose to use it. By using the website or
					game, you agree that we may collect, use, disclose, and process your information in the manner described in this privacy
					policy. This privacy policy only applies to websites and games, and does not apply to any other websites, products or
					services that you may access or link to through websites or games. We encourage you to read the privacy policies of any
					other websites you visit before providing them with your information. Although our values will not change, websites and
					games will evolve over time, and this privacy policy will change accordingly to reflect this development. If we make any
					changes, we will notify you by revising the date at the top of this privacy policy. In some cases, if we make
					significant changes, we may provide you with additional notifications by adding a statement on our homepage. We
					encourage you to regularly review this privacy policy to understand our practices. Some third-party providers may place
					cookies or pixels on your browser or hard drive - small data files stored in your hard drive or device memory. Please
					note that this privacy policy does not cover the use of cookies or pixels by such third parties. Most web browsers are
					set to accept cookies and pixels by default, but you can usually set your browser to delete or reject browser cookies or
					pixels. However, if you choose to delete or reject cookies or pixels, your ability to use the website or game may be
					affected.
				</p>
				<p>
					1.2 This Privacy Policy should be read in conjunction with our Terms of Use. By accessing the game, you agree to the
					information collection and usage practices described in this Privacy Policy.
				</p>
				<p>
					1.3 Your use of the game and any personal information you provide through the game remain bound by this privacy policy
					and our terms of use, each of which may be updated from time to time.
				</p>
				<p>1.4 Any questions, comments or complaints you may send via email to services@simsports.io</p>
				<h2>2. The information we collect</h2>
				<p>The personal information we collect from you may typically include:</p>
				<p>
					2.1 Network information related to transactions, including but not limited to the type of device you are using, access
					time, hardware model, MAC address, IP address, operating system and OS version, and other unique device identifiers.
				</p>
				<p>
					2.2 The plugin information you may use, including but not limited to plugins related to cryptocurrency asset management
					and any information they provide, as well as your BNB Chain public address.
				</p>
				<p>2.3 We may receive network information from you due to your interaction with our game.</p>
				<p>
					2.4 When you register as a user, we may collect the following personal information from you: your email address and
					username. After registration, we allow you to link to third-party social network accounts. In this case, we may receive
					personal information you provide to these third parties, and you have allowed them to forward it through your privacy
					settings.
				</p>
				<h2>3. How MP uses your personal information</h2>
				<p>
					3.1 Like almost all interactions that occur on the World Wide Web, our servers may receive information, including but
					not limited to IP addresses, due to your interactions with them.
				</p>
				<p>
					3.2 Some services in our game require permissions, which may be used to access additional personal information. These
					permissions are only used for very limited technical purposes to allow the game to interact correctly with your browser.
					We will not obtain any other information except for providing necessary information for the game. Without your consent,
					the received information will not be shared with any third party, unless these third parties are associated with MP or
					necessary for providing games.
				</p>
				<p>
					3.3 MP collects usage data to monitor network traffic and improve our products. Any identification information collected
					through ThinkingData is controlled by ThinkingData.
				</p>
				<p>
					3.4 Public blockchain provides transparency for transactions, and MP is not responsible for preventing or managing
					information broadcasted on the blockchain.
				</p>
				<h2>4. How do we handle the collected information</h2>
				<p>4.1 MP may use the information we collect in the following ways:</p>
				<p>• Analyze trends in website and game usage;</p>
				<p>• Improve websites and games;</p>
				<p>• Help personalize your website and gaming experience;</p>
				<p>
					• If you provide us with your contact information, we may use it to contact you, send you technical notifications,
					updates, confirmations, security alerts, provide support, inform you of other products and services that we believe may
					be of interest to you, or respond to your comments or questions;
				</p>
				<p>
					• If you link to a social network account, we may share your achievements and goals in the game on relevant social
					networks.
				</p>
				<p>• Your SimSports.io account username will be used in the game and can be seen by other game users</p>
				<p>
					4.2 MP may share the information we collect with third parties who need to access it to complete the work on our behalf,
					including but not limited to helping us make the website or game available, including but not limited to payment service
					providers, anti fraud service providers, or providing analysis services for us. We strive to ensure that these third
					parties only access and use your information as needed to complete their functions.
				</p>
				<p>
					4.3 MP may create aggregations and anonymities that contain your information, but it will not directly identify you. MP
					can use and/or share these aggregations and anonymities for various purposes related to websites, games, or our company
					and its business.
				</p>
				<p>
					4.4 MP may disclose your personal information to our subsidiaries, affiliates, agents, businesses, or service providers
					who process your services on our behalf. Our agreements with these service providers limit the types of information they
					can use or process, and ensure that they do their best to protect the security of your personal information.
				</p>
				<p>
					4.5 MP also reserves the right to disclose with reasonable confidence any personal information that MP deems appropriate
					or necessary to enforce our terms of use, take preventive measures to prevent liability or damage, investigate and
					respond to third-party claims or accusations, respond to court orders or official requests, protect the safety or
					integrity of our game, and protect the rights, property, or safety of MP, our users, or others.
				</p>
				<p>
					4.6 If MP is involved in events such as mergers, acquisitions, sales, bankruptcy, reorganization, takeover, distribution
					for the benefit of creditors, or changes in control of laws or principles of fairness applicable to creditor rights, it
					may disclose your information to another entity related to such events.
				</p>
				<h2>5. Your Choice</h2>
				<p>
					MP will process your personal information in accordance with this privacy policy, and as part of this section, you will
					have little or no opportunity to modify how MP uses your information.
				</p>
				<h2>6. Cookies</h2>
				<p>
					Our website uses' Cookies', which are text files placed on your computer that help MP analyze how users use the website,
					as well as similar technologies such as network beacons, pixels, advertising labels, and device identifiers, to identify
					you and/or your device on our website, shut down, and cross different devices. The use of cookies is standard on the
					internet. Although most web browsers automatically accept cookies, the decision to accept or not is up to you. You can
					adjust your browser settings to prevent the use of cookies, or provide notifications every time cookies are sent. You
					can choose to reject the use of cookies in the appropriate settings on the browser. However, please note that if you do
					so, you may not be able to access all the features of our website.
				</p>
				<h2>7. Information we do not collect</h2>
				<p>
					We will not collect any other personally identifiable information from you unless you provide it directly to us: by
					filling out a form, providing us with written feedback, communicating with us through third-party social media websites,
					or communicating with us through websites, games, or any other means.
				</p>
				<h2>8. Information Security</h2>
				<p>
					Although we and any other organization cannot guarantee the security of information processed online, we have indeed
					taken appropriate security measures to protect your personal information. For example, we store the personal information
					you provide on a computer system with limited access, encryption, or both.
				</p>
				<h2>9. Privacy Rights</h2>
				<p>
					According to applicable laws, you may have some or all of the following rights to your personal information: (i) Obtain
					copies of your personal information and information on how and on what basis to process that personal information; (ii)
					Correcting inaccurate personal information (including the right to complete incomplete personal information); (iii)
					Delete your personal information in limited circumstances (when it is no longer related to the purpose of collection or
					processing); (iv) Restrict the processing of your personal information under the following circumstances: a Some people
					question the accuracy of personal information; b. Processing is illegal, but you oppose deleting personal information;
					Or c. We no longer need personal information, but it still needs to be claimed, exercised, or defended in accordance
					with legal requirements; (v) Challenge our handling based on legitimate interests (rather than relying on your consent
					or signing a contract with you); (vi) Prevent us from sending direct marketing messages to you; (vii) Withdraw your
					consent to our processing of your personal information (if such processing is based on your consent); (viii) Oppose
					decisions solely based on automated processing or analysis; (ix) In addition to the above, you have the right to file a
					complaint with regulatory authorities.
				</p>
				<h2>10. Changes and Updates</h2>
				<p>
					10.1 This privacy policy may be revised periodically, which will be reflected in the "Latest update" mentioned above.
					Please revisit this page to learn about any changes. Your continued use of the game constitutes your consent to this
					privacy policy and any future revisions.
				</p>
				<p>10.2 Contact us: services@simsports.io</p>
			</div>
		</div>
	);
};

export default View;

// simsports-3.0-pc/src/views/privacypolicy/index.vue
<!-- privacypolicy -->
<template>
	<div class="main">
		<div class="privacypolicy-box">
			<h1>PRIVACY POLICY</h1>
			<p>
				Welcome to the website and mobile apps owned and operated by METAPROPHET Games (Singapore) Co.,Limited and its affiliates
				(" METAPROPHET ," "we" or "us"),and METAPROPHET is committed to protecting your privacy. This Privacy Policy explains how
				information about you or associated with you ("personal information") is collected, used and disclosed by METAPROPHET.
				This Privacy Policy applies to our websites, including our mobile apps for iPhone, Android devices (collectively, "our
				Service"). By accessing or using our Service, you signify that you have read, understood and agree to our collection,
				storage, use and disclosure of your personal information as described in this Privacy Policy.
			</p>
			<p>
				This Privacy Policy describes why and how we collect, store, and use your personal data, and the choices and rights you
				have about the personal data you provide or we collect in connection with the METAPROPHET Services. If you have any
				questions about this Privacy Policy, please contact us using the contact details provided in “Contact and Complaint” of
				this Privacy Policy.
			</p>
			<!-- <h2>Table of Contents</h2>
			<h3>1. INFORMATION WE COLLECT AND USE</h3>
			<h3>2. SHARING INFORMATION</h3>
			<h3>3. YOUR CHOICES REGARDING YOUR INFORMATION</h3>
			<h3>4. SECURITY AND STORAGE OF INFORMATION</h3>
			<h3>5. PERSONS UNDER THE AGE OF 13</h3>
			<h3>6. SENSITIVE PERSONAL DATA</h3>
			<h3>7. COMPLAINTS</h3>
			<h3>8. EU-U.S. PRIVACY SHIELD</h3>
			<h3>9. LINKS TO THIRD PARTY WEBSITES</h3>
			<h3>10. UPDATES TO THIS POLICY</h3>
			<h3>11. USERS IN THE EEA</h3>
			<h3>12. USERS IN CALIFORNIA</h3>
			<h3>13. CONTACTING US</h3>
			<h3>14. LAST REVISION DATE</h3>-->
			<h3>1. INFORMATION WE COLLECT AND USE</h3>
			<p>
				Generally. We will only process your personal data in accordance with applicable data protection and privacy laws. We
				collect personal information from our users in order to provide you with a personalized, useful and efficient experience.
				If you created a profile/registered with us, you will have been asked to tick to agree to provide this information in
				order to access our Services. This consent provides us with the legal basis we require under applicable law to process
				your data. You maintain the right to withdraw such consent at any time. If you do not agree to our use of your personal
				data in line with this Policy, please do not use our Service.
			</p>
			<p>
				The categories of information we collect can include: Information you provide. You may use the Service without providing
				any personal information, but you must register and create a profile to participate in our official forums. We may collect
				and store personal information when you register for our Service or provide to us in some other manner, including your
				name, email address, user name and password. We may also collect any communications between you and METAPROPHET , as well
				as any information you provide if you take part in any interactive features of the Service. Information that is part of
				your profile will be viewable to the public and to other members of the Service.
			</p>
			<p>
				Data collected through the use of the Service. After you set up your account, you may choose to provide additional
				information which may be shared through public profiles, such as your photograph or avatar, biographical content, and
				other information (collectively, "Profile Information"). You control how much personally identifying information you wish
				to provide in your public profile. We also collect information about how you use the Service and about your actions on the
				Service, including your Service usage and activities, gaming levels, interactions with others on the Service and user
				content you post to the Service, and other content ("User Content"). Please remember that METAPROPHET may, but has no
				obligation to, monitor User Content posted by our members.
			</p>
			<p>
				Information we receive from third party sites. When you interact with our site through various social media, such as when
				you login through Facebook, Google + or another third party service, or share content on Facebook, Twitter or other sites,
				we may receive information from the social network including your profile information, profile picture, gender, user name,
				user ID associated with your social media account, age range, language, country, friends list, and any other information
				you permit the social network to share with third parties. We may use your friends data to let you know what your friends
				are doing on our Service, and to let your friends know what you are doing on the Service. The data we receive is dependent
				upon your privacy settings with the social network, and we will not post information about you on third party social media
				sites without your consent. You should always review, and if necessary, adjust your privacy settings on third-party
				websites and services before linking or connecting them to our website or Service.
			</p>
			<p>
				We use this information to operate, maintain, and provide to you the features and functionality of the Service, as well as
				to communicate directly with you, such as to send you email messages and push notifications, and permit you to communicate
				with others on the Service or on social media or invite others to join the Service. We may combine information internally
				across different Service offerings or games to enhance your experience with our Service. For example, we may identify a
				friend you may know from one service to suggest that you engage with that friend on another service, and we may let your
				friends on one service know about your activities on another service. For example, we may send an email to your friends on
				one of our Games to let them know that you're active on our Games, and we may include your profile picture in the email so
				that your friends recognize you. We may also use information about your activities on the Service to provide personalized
				content, including targeted content and advertising. We may also send you Service-related emails or messages (e.g.,
				account verification, account status, change or updates to features of the Service, technical and security notices). For
				more information about your communication preferences, see "Your Choices Regarding Your Information" below.
			</p>
			<h3>2. SHARING INFORMATION</h3>
			<p>
				We may share your personal information in the instances described below. For further information on your choices regarding
				your information, see the "Your Choices Regarding Your Information" section below.
			</p>
			<p>We may also share your personal information with:</p>
			<p>
				a.Third parties at your request. For example, you may have the option to share your activities on METAPROPHET with your
				friends through email, text or on various social media sites;
			</p>
			<p>
				b.Other brands owned or controlled by METAPROPHET and other companies owned by or under common ownership as METAPROPHET ,
				which also includes our subsidiaries (i.e., any organization we own or control) or our ultimate holding company (i.e., any
				organization that owns or controls us) and any subsidiaries it owns. These companies will use your personal information in
				the same way as we can under this Policy;
			</p>
			<p>
				b.Other brands owned or controlled by METAPROPHET and other companies owned by or under common ownership as METAPROPHET ,
				which also includes our subsidiaries (i.e., any organization we own or control) or our ultimate holding company (i.e., any
				organization that owns or controls us) and any subsidiaries it owns. These companies will use your personal information in
				the same way as we can under this Policy;
			</p>
			<p>
				d.Third party vendors, consultants and other service providers that perform services on our behalf, in order to carry out
				their work for us, which may include identifying and serving targeted advertisements, content or service fulfillment, or
				providing analytics services;
			</p>
			<p>
				e.Other parties in connection with any company transaction, such as a merger, sale of all or a portion of company assets
				or shares, reorganization, financing, change of control or acquisition of all or a portion of our business by another
				company or third party or in the event of bankruptcy or related or similar proceedings; and
			</p>
			<p>
				f.Third parties as required to ( i ) satisfy any applicable law, regulation, subpoena/court order, legal process or other
				government request, (ii) enforce our Terms of Use Agreement, including the investigation of potential violations thereof,
				(iii) investigate and defend ourselves against any third party claims or allegations, (iv) protect against harm to the
				rights, property or safety of METAPROPHET , its users or the public as required or permitted by law and (v) detect,
				prevent or otherwise address criminal (including fraud or stalking), security or technical issues.
			</p>
			<p>
				We may also share information with others in an aggregated and anonymous form that does not reasonably identify you
				directly as an individual.
			</p>
			<h3>3. YOUR CHOICES REGARDING YOUR INFORMATION</h3>
			<p>Profile and Data Sharing Settings. You may change some of your data sharing preferences on your Settings page.</p>
			<p>
				Push Notifications.We may occasionally send you push notifications through our mobile applications to send you game
				updates, high scores and other service related notifications that may be of importance to you. You may at any time opt-out
				from receiving these types of communications by turning them off at the device level through your settings.
			</p>
			<p>
				Marketing Communications. If you do not wish to receive promotional emails, you can click the "unsubscribe" button on
				promotional email communications. Note that you are not permitted to unsubscribe or opt-out of non-promotional messages
				regarding your account, such as account verification, change or updates to features of the Service, or technical and
				security notices.
			</p>
			<p>
				Online Advertising.We may permit third party online advertising networks, social media companies, and other parties to
				collect information about your use of our website and apps over time so that they may play or display ads that may be
				relevant to your interests on our Service as well as on other websites or apps. Typically, the information we share is
				provided through cookies or similar tracking technologies. The only way to completely "opt out" of the collection of any
				information through cookies or other tracking technology is to actively manage the settings on your browser or mobile
				device. Please refer to your browser's or mobile device's technical information for instructions on how to delete and
				disable cookies, and other tracking/recording tools. (To learn more about cookies, clear gifs/web beacons and related
				technologies, you may wish to visit http://www.allaboutcookies.org and/or the Network Advertising Initiative's online
				resources, at https://www.networkadvertising.org ). If you access our service on your mobile device, you may not be able
				to control tracking technologies through settings.
			</p>
			<p>
				Data Retention: We will retain your information for as long as your account is active or as needed to provide you
				services. Please contact us at services@simsports.io if you wish to delete your account permanently from our systems.
				Please be aware that we will not be able to delete any content you have shared with others or with social media sites.
			</p>
			<p>
				Deleting or Anonymizing Your Content: If you are under 18 years of age, you may request that the User Content that you
				posted to our Service be deleted or anonymized such that your personal information will not be identifiable publicly on
				our Service by contacting us at services@simsports.io . While we will use all commercially reasonable efforts to delete or
				anonymize your User Content upon request, please be aware that due to the social nature of our Service, you may not be
				able to completely remove all of your personally identifiable User Content if, for example, that content has been stored,
				republished, or reposted by another user or a third party. We may also maintain your information in identifiable form for
				our internal use, even if your personal data is no longer visible to the public on our Service.
			</p>
			<h3>4. SECURITY AND STORAGE OF INFORMATION</h3>
			<p>
				METAPROPHET cares about the security of your information and uses commercially reasonable physical, administrative, and
				technological safeguards to preserve the integrity and security of all information we collect and that we share with our
				service providers. However, no security system is impenetrable and we cannot guarantee the security of our systems 100%.
				In the event that any information under our control is compromised as a result of a breach of security, we will take
				reasonable steps to investigate the situation and where appropriate, notify those individuals whose information may have
				been compromised and take other steps, in accordance with any applicable laws and regulations.
			</p>
			<p>
				Your information collected through our Service may be stored and processed in Hong Kong or any other country or region in
				which METAPROPHET or its subsidiaries, affiliates or service providers maintain facilities. If you are located in the
				European Union or other regions with laws governing data collection and use that may differ from Hong Kong law, please
				note that we may transfer information, including personal information, to a country and jurisdiction that does not have
				the same data protection laws as your jurisdiction, and you consent to the transfer of information to Hong Kong or any
				other country or region in which Company or its parent, subsidiaries, affiliates or service providers maintain facilities
				and the use and disclosure of information about you as described in this Privacy Policy.
			</p>
			<h3>5. PERSONS UNDER THE AGE OF 13</h3>
			<p>
				The Service and its content are not directed at children under the age of 13. In the event that we learn that we have
				collected personal information from a child under age 13 without parental consent, we will delete that information as
				quickly as possible. If you believe that we might have any information collected from a child under 13, please contact us
				at services@simsports.io.
			</p>
			<h3>6. SENSITIVE PERSONAL DATA</h3>
			<p>
				Subject to the following paragraph, we ask that you not send us, and you not disclose, any sensitive personal data (e.g.,
				social security numbers, information related to racial or ethnic origin, political opinions, religion or other beliefs,
				health, biometrics or genetic characteristics, criminal background or trade union membership) on or through our Forums,
				Social Media, Service or otherwise to us.
			</p>
			<p>
				If you send or disclose any sensitive personal data to us when you submit user generated content to our Forums, Social
				Media or Service, you consent to our processing and use of such sensitive personal data in accordance with this Policy. If
				you do not consent to our processing and use of such sensitive personal data, you must not submit such user generated
				content to our Forums, Social Media, Service or otherwise to us.
			</p>
			<h3>7. COMPLAINTS</h3>
			<p>
				We are committed to resolve any complaints about our collection or use of your personal data. If you would like to make a
				complaint regarding this Policy or our practices in relation to your personal data, please contact us at:
				services@simsports.io. We will reply to your complaint as soon as we can and in any event, within 45 days. We hope to
				resolve any complaint brought to our attention, however if you feel that your complaint has not been adequately resolved,
				you reserve the right to contact your local data protection supervisory authority, which for the UK, is the Information
				Commissioner’s Office
			</p>
			<p>
				We are committed to processing your data in accordance with the required standards. This includes protecting your privacy
				and ensuring the security of your data in compliance with, in particular and where applicable, the requirements of the
				Personal Data (Privacy) Ordinance (Chapter 486 of the Laws of Hong Kong), Regulation (EU) 2016/679 of the European
				Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of
				personal data and on the free movement of such data where applicable.
			</p>
			<h3>8. EU-U.S. PRIVACY SHIELD</h3>
			<p>
				The Service may contain links to and from third party websites of our business partners, advertisers, social media sites,
				and our users may post links to third party websites. If you follow a link to any of these websites, please note that
				these websites have their own privacy policies and that we do not accept any responsibility or liability for their
				policies. Please check the individual policies before you submit any information to those websites.
			</p>
			<h3>9. LINKS TO THIRD PARTY WEBSITES</h3>
			<p>
				We reserve the right to modify this Policy from time to time. If we make any changes to this Policy, we will change the
				"Last Revision" date below and will post the updated Policy on this page. If you object to any changes, you may close your
				account. Continuing to use our Service after we publish changes to this Privacy Policy means that you are consenting to
				the changes.
			</p>
			<h3>10. UPDATES TO THIS POLICY</h3>
			<p>
				As set out in more detail below, we only process or transfer your personal information where we can rely on legal grounds
				and appropriate safeguards to do so. You also have additional rights regarding your personal information if you are
				located in the European Economic Area (“EEA”).
			</p>
			<p>(1) Legal Basis for Processing Your Personal Information</p>
			<p>
				We only process your personal information where we can rely on legal grounds to do so. We process your personal
				information for the purposes set out below.
			</p>
			<p>a. Performance of the Services</p>
			<p>
				We process your personal information for the performance of our services, to provide or support of our products, or for
				any other feature you request or enable. This includes, for example, using your personal information to:
			</p>
			<p>• administer your account;</p>
			<p>• provide contests or promotions in which you have enrolled;</p>
			<p>• support purchases you make; • support game functionality;</p>
			<p>• provide global customer service; or</p>
			<p>• provide a fair gaming experience by using anti-fraud technologies such as bans or blocks of accounts.</p>
			<p>b. Consent</p>
			<p>We process your personal information based on your consent. This includes, for example, providing:</p>
			<p>• newsletters, direct e-mails and surveys about our Properties; and</p>
			<p>• certain other marketing features</p>
			<p>c. Legitimate Interest</p>
			<p>
				We process your personal information where we have a legitimate interest to do so. This includes, for example, processing:
			</p>
			<p>• to provide you with requested customer service or technical support;</p>
			<p>• to debug and improve our current and future Properties;</p>
			<p>
				• in order to give you exclusive content, personalize your online experience with us and contact you in accordance with
				applicable marketing preferences; and
			</p>
			<p>
				• for the establishment, exercise or defense of legal claims or whenever courts are acting in their judicial capacity.
			</p>
			<p>d. Legal Obligation</p>
			<p>We process your personal information for compliance with a legal obligation to which we are subject.</p>
			<p>(2) Your Rights to Your Personal Information</p>
			<p>
				You have the following rights in addition to your rights to view, correct, update, or request the deletion of your
				personal information
			</p>
			<p>
				You may object to the processing of your personal information based on a legitimate interest on grounds relating to your
				particular situation. You may, in particular, control the extent to which we market to you and you have the right to
				request that we stop sending you marketing messages at any time.
			</p>
			<p>In certain circumstances, you can request that we transfer personal information that you have provided to us.</p>
			<p>
				Where we rely on your consent in order to process your personal information, you have the right to withdraw such consent
				to further use of your personal information at any time.
			</p>
			<p>For each of the rights described above, you can contact us at services@simsports.io.</p>
			<p>
				We hope that we can satisfy queries you may have about the way we process your personal information. However, if you have
				unresolved concerns you also have the right to complain to data protection authorities. You can bring the complaint in
				your member state of residence, place of work or where an alleged infringement of data protection law occurred.
			</p>
			<p>(3) International Transfers</p>
			<p>
				Your personal information will be transferred to and processed in the United States. We use European Commission approved
				contract clauses to protect your personal information. If you have questions, please contact us at services@simsports.io.
			</p>

			<h3>11. USERS IN THE EEA</h3>
			<p>
				The California Consumer Privacy Act (“CCPA”) grants California residents certain privacy rights regarding personal data we
				collect. We are committed to respecting these rights and complying with the CCPA. The following explains these rights and
				METAPROPHET's practices with respect to them.
			</p>
			<p>
				Right to Know. Under the CCPA you have the right to request that we disclose to you what personal data we collect, use,
				disclose and share.
			</p>
			<p>
				Exercising Your Rights. California residents may exercise you rights by submitting your request to us by the email:
				services@simsports.io .For security purposes, we will verify your identity – including requesting information from you –
				when you request to exercise your rights. If you have an online account you use to interact with METAPROPHET, logging into
				your account will serve to verify your identity and request. We may request additional information if we believe your
				account has been compromised. If you do not have an account with us, or if we have reasons to suspect that the security of
				your account is compromised, then we will request additional information from you to match with our existing records to
				verify your identity, depending on the nature of the request and the sensitivity of the information sought.
			</p>
			<p>
				Once we have verified your identity (and your agent, as applicable), we will respond to your request as appropriate. If we
				are unable to complete your requests, we will provide you information about the reasons that we could not comply with your
				request.
			</p>
			<p>
				Right to Request Deletion. You also have the right to request deletion of your personal data that is in our possession,
				subject to certain exceptions. Please note that your request by contacting us at; services@simsports.io to delete data may
				impact your use of our Service in some cases, and we may decline to delete information for reasons set forth in this
				Privacy Policy or as permitted by the CCPA.
			</p>
			<p>
				Other Rights. The CCPA also gives California residents a right to opt-out from the sale of their Personal Data. We do not
				sell your personal data and have not done so in the past 12 months. Furthermore, you have a right to not be discriminated
				against for exercising your rights under the CCPA.
			</p>
			<p>
				You may designate, in writing or through a power of attorney, an authorized agent to make requests on your behalf to
				exercise your rights under the CCPA. Before accepting such a request from an agent, we will require the agent to provide
				proof you have authorized it to act on your behalf, and we may need you to verify your identity directly with us.
			</p>
			<h3>12. USERS IN CALIFORNIA</h3>
			<p>If you have questions about this Privacy Policy, please contact us at services@simsports.io</p>
			<h3>13. CONTACTING US</h3>
			<p>This Policy was last revised on Feb,14th, and effective as of Feb,14th , 2023.</p>
		</div>
	</div>
</template>

<style lang="less" scoped>
.main {
	padding: 90px 0;
	.privacypolicy-box {
		width: 70%;
		margin: 0 auto;
		h1,
		h2,
		h3 {
			line-height: 50px;
		}
		p {
			line-height: 24px;
			margin-top: 10px;
		}
	}
}
</style>
