// simsports-5.0-moblie/src/views/home/index.tsx
// HOME
import React from "react";
import HomeTop from "./home-top/index";
import HomeGame from "./home-game/index";
import HomeBuild from "./home-build/index";
import HomeGovernance from "./home-governance/index";
import HomePartners from "./home-partners/index";
import HomeTeam from "./home-team/index";
import DownloadGame from "@/components/download-game/index";

const View: React.FC = () => {
	return (
		<>
			<HomeTop />
			<HomeGame />
			<HomeBuild />
			<HomeGovernance />
			<HomePartners />
			<HomeTeam />
			<DownloadGame />
		</>
	);
};

export default View;

// simsports-5.0-pc/src/views/home/index.vue
<!-- home -->
<template>
	<div id="home-box">
		<HomeTop />
		<HomeBuildVideo />
		<HomeBuild />
		<HomeGovernance />
		<HomePartners />
		<HomeTeam />
	</div>
	<DownloadGame></DownloadGame>
</template>

<script setup lang="ts">
import HomeTop from "./home-top/index.vue"; //top
import HomeBuild from "./home-build/index.vue"; //build
import HomeBuildVideo from "./home-build-video/index.vue"; //build-video
import HomeGovernance from "./home-governance/index.vue"; //governance
import HomePartners from "./home-partners/index.vue"; //partners
import HomeTeam from "./home-team/index.vue"; //TEAM
import DownloadGame from "@/components/download-game/index.vue"; //download-game
</script>

<style lang="less">
#home-box {
	width: 100%;
	font-size: 0.83333vw !important; /* 自适应 16px */
	// font-size: 0.78125vw !important; /* 自适应 15px */
	overflow-x: hidden;
	h2#home-titele {
		font-family: Quantico;
		color: @COLOR_THEME;
		font-size: 6.5em;
		line-height: 1em;
	}
}
</style>
