// simsports-5.0-moblie/src/views/governance/index.tsx
// governance
import React from "react";
import GovernanceTop from "./governance-top/index";
import GovernanceToken from "./governance-token/index";
import GovernanceUtilities from "./governance-utilities/index";
const View: React.FC = () => {
	return (
		<>
			<GovernanceTop />
			<GovernanceToken />
			<GovernanceUtilities />
		</>
	);
};

export default View;

// simsports-5.0-pc/src/views/governance/index.vue
<!-- governance -->
<template>
	<GovernanceTop />
	<GovernanceToken />
	<GovernanceUtilities />
</template>

<script setup lang="ts">
// import { ref, reactive } from "vue";
import GovernanceTop from "./governance-top/index.vue";
import GovernanceToken from "./governance-token/index.vue";
import GovernanceUtilities from "./governance-utilities/index.vue";
</script>
