// simsports-5.0-moblie/src/views/simdunk/simdunk-palyer-menu/game-palyer/index.tsx
// game-palyer
import React, { useState, useEffect, useRef } from "react";
import "./index.less";

import Slider from "react-slick"; //slick轮播图
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { Image } from "antd-mobile";
import { LeftOutline } from "antd-mobile-icons";

interface InputProps {
	display: boolean;
	palyerData: any;
	onHandlePalyerChange: (display: boolean, palyerType: string) => void;
}
const View: React.FC<InputProps> = ({ display, palyerData, onHandlePalyerChange }: InputProps) => {
	console.log(palyerData);

	// 点击后退图片
	const handleViewChange = () => {
		onHandlePalyerChange(!display, "");
	};

	// swiper
	const palyerSlider = useRef<typeof Slider | null>(null); //Palyer-swiper
	const palyerAvatarSlider = useRef<typeof Slider | null>(null); //Palyer-Avatar-swiper
	const [palyerNav, setPalyerNav] = useState(null); //赋值-Palyer-swiper
	const [palyerAvatarNav, setPalyerAvatarNav] = useState(null); //赋值-Palyer-Avatar-swiper
	useEffect(() => {
		setPalyerNav(palyerSlider.current);
		setPalyerAvatarNav(palyerAvatarSlider.current);
	}, []);
	const [activeSwiper, setActiveSwiper] = useState<number>(0); //定义swiper索引
	const palyerSettings = {
		slidesToShow: 1, //一帧显示
		arrows: false, //切换箭头
		fade: true, //淡出淡入
		infinite: false, //无限滑动
		touchMove: false, //手动切换
		afterChange: (index: any) => {
			setActiveSwiper(index);
		},
		// asNavFor: palyerAvatarNav.current, //同步另一个滑块
	};
	const palyerAvatarSettings = {
		slidesToShow: 4,
		arrows: false,
		infinite: false,
		touchMove: false, //手动切换
		swipeToSlide: true, //启用拖动/滑动
		focusOnSelect: true, //点击切换
	};
	// 链接跳转
	const goLink = () => {
		window.open(palyerData.list[activeSwiper].palyerLink, "_blank");
	};
	return (
		<>
			<div className="game-palyer">
				<Image src={palyerData.bgImg} className="game-tab-bg" />
				<div className="game-palyer-box">
					<div className="main">
						<LeftOutline
							className="icon-outline"
							onClick={() => {
								handleViewChange();
							}}
						/>
						{/* 第一个swiper */}
						<Slider
							className="game-palyer-slider"
							ref={(slider: null) => (palyerSlider.current = slider)}
							asNavFor={palyerAvatarNav}
							{...palyerSettings}
						>
							{palyerData.list.map((item: any, index: any) => (
								<div className="swiper-box" key={index}>
									<div className="center">
										<div className="game-palyer-img-box">
											<Image src={item.palyerImg} className="game-palyer-img" />
										</div>
										<h2 className="game-palyer-title">{item.name}</h2>
										<p className="fillet-paragraph-text02">{item.nickname}</p>
										<p className="fillet-paragraph-text04">{item.introduce}</p>
										{palyerData.list[activeSwiper].palyerLink ? (
											<button
												className="fillet-diamond-button"
												onClick={() => {
													goLink();
												}}
											>
												ROLE GAMEPLAY
											</button>
										) : (
											<button className="fillet-diamond-button-disabled">COMING SOON</button>
										)}
									</div>
								</div>
							))}
						</Slider>
						{/* 第二个swiper切换 */}
						<div className="game-palyer-change">
							{palyerData.list.length > 1 ? (
								<Image
									src={palyerData.changeButton[0]}
									className="icon-change icon-change-prev"
									onClick={() => {
										palyerSlider.current.slickPrev();
									}}
								/>
							) : (
								<></>
							)}
							{/* 第二个swiper */}
							<div className="game-avatar-swiper">
								<Slider
									className="game-avatar-slider"
									ref={(slider: null) => (palyerAvatarSlider.current = slider)}
									asNavFor={palyerNav}
									{...palyerAvatarSettings}
								>
									{palyerData.list.map((item: any, index: any) => (
										<div className="swiper-box" key={index}>
											<div className="center">
												<Image
													style={index === activeSwiper ? palyerData.active : {}}
													src={item.palyerAvatarImg}
													className="game-avatar-img"
												/>
											</div>
										</div>
									))}
								</Slider>
							</div>
							{palyerData.list.length > 1 ? (
								<Image
									src={palyerData.changeButton[1]}
									className="icon-change icon-change-next"
									onClick={() => {
										palyerSlider.current.slickNext();
									}}
								/>
							) : (
								<></>
							)}
						</div>
					</div>
				</div>
				<div className="game-palyer-bg" style={palyerData.backgroundColor}></div>
			</div>
		</>
	);
};
export default View;

// simsports-5.0-pc/src/views/simdunk/simdunk-palyer-menu/game-palyer/index.vue
<!-- game-palyer  -->
<template>
	<div class="game-palyer">
		<!-- 背景图 -->
		<div class="game-palyer-bg">
			<el-image :src="palyerData.bgImg" class="game-play-bg-img" />
		</div>
		<div class="main">
			<div class="game-palyer-title">
				<el-icon class="icon-left" @click="exhibitData.display = true"><ArrowLeftBold /></el-icon>
				<el-image :src="palyerData.titleImg" class="game-palyer-title-img" />
			</div>
			<!-- one-swiper -->
			<div class="game-palyer-box">
				<Splide ref="palyerSlider" :options="{ ...palyerSettings }" class="game-palyer-swiper">
					<SplideSlide v-for="(item, index) in palyerData.list" :key="index">
						<el-image :src="item.palyerImg" class="game-player-people" />
						<button v-if="item.palyerLink" class="fillet-diamond-button" @click="goLink(item.palyerLink)">ROLE GAMEPLAY</button>
						<button v-else class="fillet-diamond-button-disabled">COMING SOON</button>
					</SplideSlide>
				</Splide>
			</div>
		</div>
		<div class="game-palyer-change" :style="palyerData.backgroundColor">
			<!-- two-swiper -->
			<div class="main game-avatar-box">
				<el-image
					v-if="palyerData.list.length > 1"
					:src="palyerData.changeButton[0]"
					class="icon-change"
					@click="changeCvImg('prev')"
				/>
				<div class="game-avatar-list">
					<div class="game-avatar-swiper-center" :style="{ width: activeSwiper.width }">
						<Splide
							ref="palyerAvatarSlider"
							class="game-avatar-swiper"
							:options="{ ...palyerAvatarSettings, perPage: activeSwiper.swiperNum }"
							@splide:mounted="onSplideMounted"
							@splide:move="onSplideMove"
						>
							<SplideSlide v-for="(item, index) in palyerData.list" :key="index">
								<div class="swiper-box">
									<el-image
										:src="item.palyerAvatarImg"
										class="game-player-img"
										:style="index === activeSwiper.activeNum ? palyerData.active : {}"
									/>
								</div>
							</SplideSlide>
						</Splide>
					</div>
				</div>
				<el-image
					v-if="palyerData.list.length > 1"
					:src="palyerData.changeButton[1]"
					class="icon-change"
					@click="changeCvImg('next')"
				/>
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from "vue";
import { Splide as Core, Options } from "@splidejs/splide";
import { Splide, SplideSlide } from "@splidejs/vue-splide"; //vue-splide-swiper组件
import "@splidejs/splide/dist/css/themes/splide-default.min.css"; //vue-splide-swiper组件样式
// 接受父组件数据
const props = defineProps({
	exhibitData: {
		type: Object,
		default: () => {},
	},
	palyerData: {
		type: Object,
		default: () => {},
	},
});
const exhibitData = reactive(props.exhibitData);
// 接收palyer展示数据
const palyerData = reactive(props.palyerData);
// swiper
const palyerSlider = ref<InstanceType<typeof Splide>>(); //Palyer-swiper
const palyerAvatarSlider = ref<InstanceType<typeof Splide>>(); //PalyerAvatar-swiper
const activeSwiper = reactive({
	activeNum: 0, //定义swiper索引
	width: "100%", //定义swiper宽度
	swiperNum: 5, //定义swiper数量显示数量
});
// swiper --vue-splide --Options
const palyerSettings: Options = {
	type: "fade", //轮播动画
	arrows: false, //箭头
	pagination: false, //指示点
	perPage: 1, //一帧显示
	drag: false, //禁止拖动
};
const palyerAvatarSettings: Options = {
	type: "slide",
	arrows: false,
	pagination: false,
	// perPage: activeSwiper.swiperNum,
	perMove: 1, //一次切换一张
	drag: false,
	isNavigation: true, //点击切换
};
// 绑定两个轮播图的光关联
const bindingSplide = () => {
	const thumbsSplide = palyerAvatarSlider.value?.splide;
	if (thumbsSplide) {
		palyerSlider.value?.sync(thumbsSplide);
	}
};
// 监听swiper切换
const onSplideMove = (_splide: any, index: number) => {
	activeSwiper.activeNum = index;
};
// 处理swiper 显示数量--宽度
const onSplideMounted = (splide: Core) => {
	if (splide.length >= 5) {
		activeSwiper.swiperNum = 5;
		activeSwiper.width = "100%";
	} else {
		activeSwiper.swiperNum = splide.length;
		activeSwiper.width = 1.48 * splide.length + "rem";
	}
};
// 切换轮播图按钮
const changeCvImg = (e: any) => {
	if (palyerAvatarSlider.value) {
		e == "prev" ? palyerAvatarSlider.value.go("<") : palyerAvatarSlider.value.go(">");
	}
};
const goLink = (link: any) => {
	window.open(link, "_blank");
};
onMounted(async () => {
	await bindingSplide();
});
</script>

<style lang="less" scoped>
// 去除vue-splide默认样式
.splide__track--nav > .splide__list > .splide__slide {
	border: none;
}
.splide__track--nav > .splide__list > .splide__slide.is-active {
	border: none;
}
.game-palyer {
	position: relative;
	min-width: 12rem;
	height: 10.8rem;
	overflow: hidden;
	.game-palyer-bg {
		width: 19.2rem;
		position: absolute;
		left: 50%;
		transform: translateX(-50%);
		.game-play-bg-img {
			.w-h(19.2rem,10.8rem);
			opacity: 0.15;
		}
	}
	.main {
		.game-palyer-title {
			margin-top: 0.64rem;
			.mixin-flex (row,flex-start,center,nowrap);
			.icon-left {
				font-size: 0.28rem;
				cursor: pointer;
			}
			.game-palyer-title-img {
				height: 1.68rem;
			}
		}
		.game-palyer-box {
			margin-top: -0.16rem;
			position: relative;
			width: 12rem;
			.game-palyer-swiper {
				width: 100%;
				.game-player-people {
					width: 12rem;
				}
				.fillet-diamond-button {
					position: absolute;
					bottom: 0.74rem;
					right: 0.76rem;
					.w-h(2.44rem,0.5rem);
					font-size: 0.24rem;
					clip-path: polygon(0.15rem 0, 100% 0, 100% calc(100% - 0.15rem), calc(100% - 0.15rem) 100%, 0 100%, 0 0.15rem);
				}
				.fillet-diamond-button-disabled {
					position: absolute;
					bottom: 0.74rem;
					right: 0.76rem;
					.w-h(2.44rem,0.5rem);
					font-size: 0.24rem;
					clip-path: polygon(0.15rem 0, 100% 0, 100% calc(100% - 0.15rem), calc(100% - 0.15rem) 100%, 0 100%, 0 0.15rem);
				}
			}
		}
	}
	.game-palyer-change {
		height: 1.8rem;
		margin: 0 auto;
		position: relative;
		min-width: 12rem;
		max-width: 19.2rem;
		.mixin-flex (column,center,center,nowrap);
		.game-avatar-box {
			.mixin-flex (row,center,center,nowrap);
			.icon-change {
				.w-h(0.4rem,0.4rem);
				margin: 0 0.38rem;
				cursor: pointer;
			}
			.game-avatar-list {
				width: 7.5rem;
				.mixin-flex (row,center,center,nowrap);
				.game-avatar-swiper-center {
					width: 100%;
					.game-avatar-swiper {
						width: 100%;
						.swiper-box {
							.mixin-flex (row,center,center,nowrap);
							.game-player-img {
								.w-h(0.92rem,0.92rem);
								border: 0.04rem solid #999;
								border-radius: 0.08rem;
								margin: 0 0.25rem;
								cursor: pointer;
								opacity: 0.6;
								&:hover {
									opacity: 1;
								}
							}
						}
					}
				}
			}
		}
	}
}
</style>
